# Generated by Django 2.2.4 on 2019-08-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0008_auto_20190820_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Student')),
            ],
            options={
                'ordering': ['-disbursed_date', '-approved_date', '-modified_date'],
            },
        ),
    ]
