# Generated by Django 2.2.4 on 2019-08-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0002_grant_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='student',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='portfolio.Student'),
        ),
    ]
