# Generated by Django 2.2.4 on 2019-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0003_auto_20190820_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='donor',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
