# Generated by Django 2.2.4 on 2019-08-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0006_auto_20190820_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='purpose',
            field=models.CharField(choices=[('TUITION', 'TUITION'), ('STIPEND', 'STIPEND'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=20),
            preserve_default=False,
        ),
    ]
