# Generated by Django 2.2.4 on 2019-08-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0005_auto_20190819_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='ResultBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.School')),
                ('semester', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.Semester')),
                ('student', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Student')),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E+', 'E+'), ('E', 'E'), ('E-', 'E-'), ('F', 'F')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.ResultBook')),
                ('subject', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.Subject')),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
    ]
