# Generated by Django 2.2.4 on 2019-08-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20190820_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.AlterField(
            model_name='result',
            name='parent',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academic.Resultbook'),
        ),
        migrations.AlterField(
            model_name='resultbook',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.School'),
        ),
        migrations.AlterField(
            model_name='resultbook',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.Semester'),
        ),
        migrations.AlterField(
            model_name='resultbook',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultbooks', to='portfolio.Student'),
        ),
        migrations.AddField(
            model_name='resultbook',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.Level'),
        ),
    ]
