# Generated by Django 2.2.4 on 2019-08-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_auto_20190820_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academic.Resultbook'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.Subject'),
        ),
    ]
