# Generated by Django 2.2.4 on 2019-08-20 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_auto_20190821_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbook',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academic.Resultbook'),
        ),
    ]
