# Generated by Django 2.2.4 on 2019-08-22 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_auto_20190821_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academic.Resultbook'),
        ),
    ]
