# Generated by Django 2.2.4 on 2019-09-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_auto_20190902_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academic.Resultbook'),
        ),
    ]
