# Generated by Django 2.2.4 on 2019-09-05 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_auto_20190904_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academic.Resultbook'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
