# Generated by Django 2.2.4 on 2019-08-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190819_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='counselor',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'Counselors'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-registered_date', '-modified_date'], 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='state',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.City'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.State'),
        ),
    ]
