# Generated by Django 2.2.4 on 2019-08-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190820_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.City'),
        ),
        migrations.AddField(
            model_name='counselor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.State'),
        ),
    ]
