# Generated by Django 2.2.4 on 2019-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190820_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bank',
            field=models.CharField(choices=[('MAYBANK', 'MAYBANK'), ('BANK ISLAM', 'BANK ISLAM'), ('AFFIN BANK', 'AFFIN BANK'), ('OTHERS', 'OTHERS')], default='MAYBANK', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_no',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
