# Generated by Django 2.2.4 on 2019-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190820_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nick_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
