# Generated by Django 2.2.4 on 2019-08-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20190820_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_person',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
