# Generated by Django 2.2.4 on 2019-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20190902_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='contact_person',
        ),
        migrations.AlterField(
            model_name='student',
            name='address3',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
