# Generated by Django 2.2.4 on 2019-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/no-img.jpg', null=True, upload_to='images/'),
        ),
    ]
