# Generated by Django 2.2.4 on 2019-08-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('counseled_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Counselor')),
                ('student', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Student')),
            ],
            options={
                'ordering': ['-counseled_date', '-modified_date'],
            },
        ),
    ]
