# Generated by Django 2.2.4 on 2019-08-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='portfolio.Student'),
        ),
    ]
